### ISSUE TITLE
empty message flood on channel

### ISSUE THREAD

**Issue by sigmonsays** [euank/go-kmsg-parser#3]
After some time I see a flood of empty messages on the channel returned by Parse(). The message looks like ```priority:0 ""```. Tons of CPU gets wasted and there does not seem to be a way to detect EOF or if restarting the parser is needed. 

The example code in godmesg is what I used as a reference.  Is there something else to properly use this library?

**Comment by euank** [comment]
Hey, @sigmonsays, did you end up figuring out anything here?
I've been meaning to look into this issue to see if I could replicated it / understand it, just haven't had time yet.
