### ISSUE TITLE
Import as module is broken

### ISSUE THREAD

**Issue by mpictor** [euank/go-kmsg-parser#6]
I'm trying to convert a package from GOPATH to modules, and found I can't add this package to go.mod; no matter what I try I get an error.

I asked on gophers slack:

>> `$ GO111MODULE=auto go mod tidy`
>> ```
>> go: finding module for package github.com/euank/go-kmsg-parser/kmsgparser/v2
>> blah/path/to/pkg imports
>>         github.com/euank/go-kmsg-parser/kmsgparser/v2: module github.com/euank/go-kmsg-parser@latest found (v2.0.0+incompatible), but does not contain package github.com/euank/go-kmsg-parser/kmsgparser/v2
>> I added github.com/euank/go-kmsg-parser v2.0.1 to go.mod but then I get
>> .../go.mod:70:2: require github.com/euank/go-kmsg-parser: version "v2.0.1" invalid: should be v0 or v1, not v2
>> ```
>> I tried adding /v2 in go.mod, as well as removing it in the import line... I've not found a permutation it's happy with
>>
> It won't work unless that repo has things completely in order.  I suspect the repo had the v2.x Git tag before converting to modules and they haven't yet added the /v2 to the module name in go.mod
>  Repos that have v2.x or higher semver tags "break" when you convert them to be Go modules.
>
> The simplest change is to update the module name in `go.mod` to be `github.com/euank/go-kmsg-parser/v2`,  but that introduces a lot of side effects. The biggest being that every import of that module/package will have to be updated to append the `/v2` at the end.
> They will likely need to create another tag, such as `v2.1.0`, after making the go.mod change.

**Comment by euank** [comment]
Ah, indeed, I was supposed to add `/v2` to the end of the module name and missed that. I can fix that.

There is a working permutation though, I think.

Creating a go.mod and import that look like the following work for me, even with the incorrect module path / tag setup

[go.mod](https://github.com/euank/kitchen-sink/blob/2333e895183ce816e45de90a935c6131fe55cbb6/import-kmsg/go.mod)

```
go 1.16

require (
	github.com/euank/go-kmsg-parser v2.0.0+incompatible
)
```

[import](https://github.com/euank/kitchen-sink/blob/2333e895183ce816e45de90a935c6131fe55cbb6/import-kmsg/main.go)

```go
import (
	"github.com/euank/go-kmsg-parser/kmsgparser"
)
```

I do agree with the advice on the from the slack that I should add `/v2` to the end and tag a new release. I'll do that shortly, and verify that seems to work as I'd expect too.

**Comment by euank** [comment]
I've tagged [v2.1.0](https://github.com/euank/go-kmsg-parser/releases/tag/v2.1.0), which should fix this.

I think the usual `go get github.com/euank/go-kmsg-parser/v2` and versioned imports should work after this.

Thanks for the heads up something was wrong there, and let me know if you're still running into issues!

**Comment by mpictor** [comment]
I had a bit of headscratching before realizing my import path was wrong.
```diff
-import "github.com/euank/go-kmsg-parser/kmsgparser/v2"
+import "github.com/euank/go-kmsg-parser/v2/kmsgparser"
```

... but it's working now.

Thanks for the fast turnaround!
